version: '3.8'
services:
  nats:
    container_name: nats
    image: "nats-streaming:0.25.5-alpine"
    restart: "always"
    ports:
      - "127.0.0.1:4222:4222"

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always